"Apxáнгельст", "Arkhangelsk"
"áдрес", "address"
"Áзия", "Asia"
"Áстрахань", "Astrakhan"
"Áфрика", "Africa"
"eё", "her"
"óвощ", "vegetable"
"óфис", "office"
"óчень", "very"
"Óчень приятно.", "Very nice (to meet you)."
"ÿжинать", "to have dinner"
"а", "and, but"
"авангáрд", "avant garde"
"Австрáлия", "Australia"
"Автóбус", "bus"
"автобус", "bus"
"адрес", "address"
"актёр", "actor"
"актрńса", "actress"
"аллó", "hello (on the telephone)"
"альпинизм", "mountain climbing"
"Амéрика", "America"
"антропóлог", "anthropologist"
"апельсин", "orange"
"аппарáт", "apparatus"
"Архангельск", "Arkhangelsk"
"Арьáт", "Arbat (street in Moscow)"
"ах", "oh"
"аэропóрт", "airport"
"аэропорт", "airport"
"Бáскин-Рóббинс", "Baskin-Robbins"
"Бóстон", "Boston"
"багáж", "luggage"
"багаж", "(sg. only) luggage"
"бадминтóн", "badminton"
"Байкал", "Lake Baikal"
"Балтимóр", "Baltimore"
"банáн", "banana"
"банан", "banana"
"банк", "bank"
"бар", "bar"
"баскетбóл", "basketball"
"бейсбóл", "baseball"
"Берлин", "Berlin"
"биóлог", "biologist"
"библиотека", "library"
"Биг-Мак", "Big Mac"
"бизнесмен", "businessperson"
"билéт", "ticket"
"бокс", "boxing"
"больница", "hospital"
"брат", "brother"
"Бутербрoóд", "sandwich noun"
"бухгáлтер", "bookkeeper, accountant"
"быстро", "fast"
"в", "in, at"
"вáза", "vase"
"вáнная", "bathroom noun"
"вéчером", "in the evening"
"вóсемь", "eight"
"ваш", " вáша, вáшк, вáши,your (s)"
"Вашингтóн", "Washington"
"ветеринáр", "veterinarian"
"вещи", "things (pl.)"
"видеокамера", "video camera"
"виза", "visa"
"вилка", "fork"
"вкусно", "tasty, delicious"
"Владивостóк", "Vladivostok"
"Волга", "the Volga river"
"Волгоград", "Volgograd (city in Russia)"
"воллейбóл", "volleyball"
"вон", "over (there)"
"Воронеж", "Voronezh (city in Russia)"
"вот", "here (is)"
"вот", "here (is/are)"
"врач (pl. врачи)", "doctor"
"всегдá", "always"
"всё", "everything"
"вчерá", "yesterday"
"вы", "you (formal)"
"Вы", "you (formal)"
"Вы не знáете ...? (ты не знáешь ...?)", "Do you happen to know ...?"
"гáмбургер", "hamburger"
"гóрод", "city, town"
"газéта", "newspaper"
"гарáж", "garage"
"где", "where"
"геóлог", "geologist"
"гимнáстика", "gymnastics"
"гитáра", "guitar"
"глаз", "eye"
"говорить", "to speak"
"Голливуд", "Hollywood"
"головá", "head"
"гольф", "golf"
"горилла", "gorilla"
"город", "city"
"гостиная", "living room"
"гостиница", "hotel"
"гость", "guest"
"гулять", "to walk"
"дáча", "dacha (cottage)"
"дéвять", "nine"
"дéлать", "to do"
"дéсять", "ten"
"дóма", "at home"
"дóчка", "daughter"
"дÿмать", "to think"
"да", "yes"
"Да", "yes"
"Давáйте на (ты).", "Let's use ты."
"два", "two"
"день", "day"
"десéрт", "dessert"
"Детрóйт", "Detroit"
"джинсы", "jeans"
"Джорджтаун", "Georgetown"
"дивáн", "sofa"
"днëм", "in the afternoon"
"До зáвтра.", "See you tomorrow. (goodbye)"
"дом", "house"
"дом", "house, building"
"до свидания", "goodbye"
"доскá", "blackboard"
"доскá", "board"
"друг", "friend"
"друг", "male friend"
"дядя", "uncle"
"Еврóпа", "Europe"
"егó", "his"
"женá", "wife"
"жить", "to live"
"журнáл", "magazine"
"журналист", "journalist (male)"
"журналистка", "journalist (female)"
"зáвтракать", "to have breakfast"
"здесь", "here"
"здрáвствуй (те)", "hellow"
"здравствуйте", "hello"
"знать", "to know"
"и", "and"
"игрÿшка", "toy"
"извините", "I'm sorry, excuse (me)"
"или", "or"
"инженéр", "engineer"
"иногдá", "sometimes"
"институт", "institute"
"интерéсно", "interesting"
"интерéсно ...", "I wonder ..."
"иоябрь", "November"
"Испáния", "Spain"
"истóрик", "historian"
"их", "their"
"июль", "July"
"июнь", "June"
"кáрта", "map"
"кóка-кóла", "Coca-cola"
"кóка-кóла", "Coke"
"кóка-кóла лайт", "Diet Coke"
"кóмната", "room"
"кóрпус", "building"
"кóшка", "cat (female)"
"кÿхна", "kitchen"
"Как же так?", "How come?"
"Как интерéсно!", "How interesting!"
"калькулятор", "calculator"
"каравáн", "caravan"
"карандаш", "pencil"
"карта", "map"
"катастрóфа", "catastrophe"
"кафé", "cafe"
"кафé", "café"
"квартира", "apartment"
"Киев", "Kiev (capital of Ukraine)"
"кинотеáтр", "movie theater"
"кинотеатр", "movie theater"
"клиника", "clinic"
"ключ", "key"
"книга", "book"
"колбáса", "salami, sausage"
"коллéдж", "college"
"комната", "room"
"компьютер", "computer"
"Костромá", "Kostroma"
"костюм", "suit"
"кот", "cat (male)"
"кошка", "cat"
"крéсло", "armchair"
"красиво", "beautiful"
"Кремль", "Kremlin"
"ксéрокс", "photocopier"
"кто", "who"
"куртка", "jacket"
"лáмпа", "lamp"
"лéтом", "in the summer"
"лóжка", "spoon"
"Лóндон", "London"
"лев", "lion"
"лимузин", "limousine"
"лук", "onion"
"люк", "manhole"
"мáло", "little, few"
"мáма", "mother"
"мáсло", "butter"
"мéсяц", "month"
"мóжно", "... ? May I ... ?"
"мóре", "sea"
"мÿсор", "garbage"
"магазин", "store"
"май", "May"
"мамá", "mom"
"матемáтик", "mathematician"
"машина", "car"
"метрó", "(indecl.) metro, subway"
"метрó", "subway"
"мнóго", "much, many"
"мой", "my"
"мой", " моя, моё, мои,my, mine"
"молокó", "milk"
"монитóр", "monitor screen"
"Москвá", "Moscow (capital of Russia)"
"мост", "bridge"
"муж", "husband"
"музéй", "museum"
"мы", "we"
"Мэдисон", "Madison"
"мэр", "mayor"
"нóмер", "number"
"на", "on, in/at"
"навéрное", "probably"
"наш", " нáша, нáше, нáши,our (s)"
"не", "not"
"неплóхо", "not bad"
"нет", "no"
"Новосибирск", "Novosibirsk"
"нож", "knife"
"ноль", "zero"
"нос", "nose"
"Нью-Йóрк", "New York"
"обéд", "lunch"
"обéдать", "to have lunch"
"один", "one"
"Ой!", "Oh! Ouch!"
"окнó", "window"
"окно", "window"
"он", "he, it"
"онá", "she"
"онá", "she, it"
"они", "they"
"опáздывать", "to be late"
"Орёл", "Oryol"
"отвечáть", "to answer"
"отдыхáть", "to rest"
"отлично", "excellent"
"отлично", "excellent, great"
"официáнт", "waiter"
"официáнтка", "waitress"
"Пáвловск", "Pavlovsk (city in Russia)"
"пáпа", "dad"
"пáпа", "father"
"пáспорт", "passport"
"пóлка", "shelf"
"пóлька", "polka"
"пóчта", "post office"
"пакéт", "plastic bag"
"пакет", "plastic bag"
"парадóкс", "paradox"
"Париж", "Paris"
"парк", "park"
"певéц", "singer (male)"
"певица", "singer (female)"
"пингвин", "penguin"
"писáтель", "writer"
"писáтельица", "writer (female)"
"письмо", "letter"
"пицца", "pizza"
"Пицца Хат", "Pizza Hut"
"плóхо", "bad"
"плащ", "raincoat"
"плитá", "stove"
"по-английски", "(in) English"
"подруга", "female friend"
"подъéзд", "entrance"
"пожáлуйста", "please; go ahead; that's OK; you're welcome"
"по-мóему", "in my opinion, I think"
"помидóр", "tomato"
"по-немéцки", "(in) German"
"понимáть", "to understand"
"по-русски", "(in) Russian"
"по-французски", "(in) French"
"поэт", "poet"
"по-япóнски", "(in) Japanese"
"прáвда", "(in this case) really"
"прóсто", "simply"
"преподавáтель", "university instructor (male)"
"преподавáтельица", "university instructor (female)"
"принтер", "printer"
"программист", "programmer"
"продавéц", "salesperson (male)"
"продавщица", "salesperson (female)"
"профéссор", "professor"
"психóлог", "psychologist"
"Псков", "Pskov (city in Russia)"
"пять", "five"
"рáдио", "radio"
"рáковина", "sink"
"рáньше", "previously, used to"
"рéгби", "rugby"
"рéдко", "seldom"
"рабóта", "work"
"рабóтать", "to work"
"раз", "one (when counting)"
"ресторáн", "restaurant"
"родители", "(pl.) parents"
"Россия", "Russia"
"Ростов", "(city in Russia)"
"рот", "mouth"
"ручка", "pen"
"рыба", "fish"
"рюкзáк", "backpack"
"Рязáнь", "Ryazan"
"сáхар", "sugar"
"салáт", "salad, lettuce"
"Санкт-Петербург", "St. Petersburg"
"Сарáтов", "Saratov (city in Russia)"
"Сахалин", "Sakhalin (island)"
"свитер", "sweater"
"сегóдня", "today"
"сейчáс", "now"
"семь", "seven"
"семья", "family"
"сестра", "sister"
"сёрфинг", "surfing"
"Сидней", "Sidney"
"скáнер", "scanner"
"Скажите", " пожáлуйста ...,Please tell (me) ..."
"слóво", "word"
"слóво", "world"
"словарь", "dictionary"
"слон", "elephant"
"собáка", "dog"
"собака", "dog"
"сок", "juice"
"соль", "salt"
"сосéдка", "neighbor (female)"
"спáльня", "bedroom"
"спайт", "Sprite"
"спасибо", "thank you"
"спорт", "sport"
"спрáшивать", "to ask"
"стадиóн", "stadium"
"стол", "table"
"столóвая", "dining room"
"студéнт", "university student (male)"
"студéнтка", "university student (female)"
"стул", "chair"
"сумка", "bag, purse"
"сумка", "purse, bag"
"суп", "soup"
"сын", "son"
"сыр", "cheese"
"тéннис", "tennis"
"Тóкио", "Tokyo"
"такси", "(indecl., neut.) taxi"
"такси", "taxi"
"там", "there"
"тарéлка", "plate"
"Ташкéнт", "Tashkent (capital of Uzbekistan)"
"твой", " твоя, твоё, твои,your (s)"
"теáтр", "theater"
"телевизор", "television set"
"телефóн", "telephone"
"тётя", "aunt"
"тигр", "tiger"
"торт", "cake"
"три", "three"
"троллéйбус", "trolley bus"
"туалéт", "restroom"
"Тула", "Tula"
"Тунис", "Tunis"
"туризм", "tourism"
"Турция", "Turkey"
"тут", "here"
"ты", "you (informal)"
"угол", "corner"
"улица", "street"
"университéт", "university"
"Урал", "the Ural mountains"
"утоль", "coal"
"утром", "in the morning"
"ухо", "ear"
"учебник", "textbook"
"учитель", "grade school teacher (male)"
"учительница", "grade school teacher (female)"
"фáнта", "Fanta"
"факс", "fax"
"физик", "physicist"
"филé-о-фиш", "Filet-o-fish"
"фотóграф", "photographer"
"фотоаппарат", "camera"
"фотогрáфия", "photograph"
"фрукт", "fruit"
"футбóл", "football"
"химик", "chemist"
"хлеб", "bread"
"хоккéй", "hockey"
"холодильник", "refrigerator"
"хорошó", "good"
"центр", "downtown"
"чáйник", "teakettle"
"чáсто", "often"
"чáшка", "cup"
"чай", "tea"
"чей", "whose (m.)"
"чемодáн", "suitcase"
"чемодан", "suitcase"
"четыре", "four"
"чизбургер", "cheeseburger"
"читáть", "to read"
"что", "what"
"Что ты! (Что Вы!)", "What are you talking about? What do you mean?"
"чьё", "whose (n.)"
"чьи", "whose (pl.)"
"чья", "whose (f.)"
"шáхматы", "chess"
"шесть", "six"
"шкóльник", "grade school student (male)"
"шкóльница", "grade school student (female)"
"шкаф", "closet"
"шкаф", "closet, walk-in closet, wardrobe"
"школа", "grade school"
"шоколáд", "chocolate"
"штат", "state"
"экономист", "economist"
"эра", "era"
"это", "this (is), these (are)"
"это", "this/these (is/are)"
"юмор", "humor"
"юрист", "lawyer"
"я", "I"
"Ялта", "Yalta"
"Ярослáвль", "Yaroslavl"
